force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Books stored in a Library.</description>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Copies_Left__c.field-meta.xml
<CustomField>
    <fullName>Copies_Left__c</fullName>
    <label>Copies Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Library__c.field-meta.xml
<CustomField>
    <fullName>Library__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Library</label>
    <referenceTo>Library__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Total_number_of_copies__c.field-meta.xml
<CustomField>
    <fullName>Total_number_of_copies__c</fullName>
    <description>Total number of copies available.</description>
    <inlineHelpText>Total number of copies available.</inlineHelpText>
    <label>Copies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Library__c/Library__c.object-meta.xml
<CustomObject>
    <description>A Library where books are stored.</description>
    <label>Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LibraryController.cls
public with sharing class LibraryController {
    @AuraEnabled(cacheable = true)
    public static List<Library__c> getLibraries(){
        return [SELECT Id, Name FROM Library__c];
    }

    @AuraEnabled(cacheable = true)
    public static List<User> getUsersForLibrary(String lib){
        if(!lib.equals(''))
            return [SELECT Id, Name, Birth_Date__c, Gender__c FROM User WHERE Registration_Library__c = :lib ];
        else 
            return new List<User>();
    }

    @AuraEnabled(cacheable = true)
    public static List<Book__c> getBooksForLibrary(Id lib){
        if(lib!=null)
            return [SELECT Id, Name, Total_number_of_copies__c, Copies_Left__c FROM Book__c WHERE Library__c = :lib];
        else 
            return new List<Book__c>();
    }

}