force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Books stored in a Library.</description>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Copies_Left__c.field-meta.xml
<CustomField>
    <fullName>Copies_Left__c</fullName>
    <label>Copies Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Book&apos;s Genre.</description>
    <inlineHelpText>Book&apos;s Genre.</inlineHelpText>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Book_Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book__c/fields/Library__c.field-meta.xml
<CustomField>
    <fullName>Library__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Library</label>
    <referenceTo>Library__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Total_number_of_copies__c.field-meta.xml
<CustomField>
    <fullName>Total_number_of_copies__c</fullName>
    <description>Total number of copies available.</description>
    <inlineHelpText>Total number of copies available.</inlineHelpText>
    <label>Copies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lending__c/Lending__c.object-meta.xml
<CustomObject>
    <label>Lending</label>
    <nameField>
        <label>Lending Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lending__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <description>Book lent.</description>
    <inlineHelpText>Book lent.</inlineHelpText>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Lendings</relationshipLabel>
    <relationshipName>Lendings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lending__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Lending&apos;s End Date.</description>
    <inlineHelpText>Lending&apos;s End Date.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lending__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Lending&apos;s start date.</description>
    <inlineHelpText>Lending&apos;s start date.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lending__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who requests the lending.</description>
    <inlineHelpText>User who requests the lending.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lendings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Library__c/Library__c.object-meta.xml
<CustomObject>
    <description>A Library where books are stored.</description>
    <label>Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestManageLending.cls
@isTest
public class TestManageLending {
    private integer copiesLeft = 50;
    
    @isTest static void insertLendingNotEnded(){
        Test.startTest();
        insertTestLibraryBookAndLending(false);
        Test.stopTest();
        Book__c book = [select Copies_Left__c from Book__c where Code__c = 'TESTCODE33'];
        System.assertEquals(49, book.Copies_Left__c);  
    }
    
    @isTest static void insertLendingEnded(){
        Test.startTest();
        insertTestLibraryBookAndLending(true);
        Test.stopTest();
        Book__c book = [select Copies_Left__c from Book__c where Code__c = 'TESTCODE33'];
        System.assertEquals(50, book.Copies_Left__c);  
    }
    
    @isTest static void updateLendingNotEnded(){
        Test.startTest();
        Lending__c l = insertTestLibraryBookAndLending(false);
        Date d = Date.newInstance(2030, 2, 17);
        l.End_Date__c = d;
        update l;
        Test.stopTest();
        Book__c book = [select Copies_Left__c from Book__c where Code__c = 'TESTCODE33'];
        System.assertEquals(49, book.Copies_Left__c); 
    }
    
    @isTest static void updateLendingEnded(){
        Test.startTest();
        Lending__c l = insertTestLibraryBookAndLending(false);
        Date d = Date.newInstance(2020, 3, 17);
        l.End_Date__c = d;
        System.debug(d);
        update l;
        Test.stopTest();
        Book__c book = [select Copies_Left__c from Book__c where Code__c = 'TESTCODE33'];
        System.assertEquals(50, book.Copies_Left__c); 
    }
    
    @isTest static void deleteLendingEnded(){
        Test.startTest();
        Lending__c l = insertTestLibraryBookAndLending(true);
        delete l;
        Test.stopTest();
        Book__c book = [select Copies_Left__c from Book__c where Code__c = 'TESTCODE33'];
        System.assertEquals(50, book.Copies_Left__c); 
    }
    
    @isTest static void deleteLendingNotEnded(){
        Test.startTest();
        Lending__c l = insertTestLibraryBookAndLending(false);
        delete l;
        Test.stopTest();
        Book__c book = [select Copies_Left__c from Book__c where Code__c = 'TESTCODE33'];
        System.assertEquals(50, book.Copies_Left__c); 
    }
    
    private static Lending__c insertTestLibraryBookAndLending(boolean isEnded){
        
        User u = [SELECT id from user where username = 'mdantonio@deloitte.it.esedoardodellacqua'];
        
        Library__c library = new Library__c(Name = 'TestLibrary');
        insert library;
        
        Book__c book = new Book__c(Code__c = 'TESTCODE33', Name = 'TestBook', Genre__c = 'Tragedy', Library__c = library.id, Total_number_of_copies__c = 50, Copies_Left__c = 50);
    	insert book;
        
        Date d;
        
        if(isEnded){
           d = Date.newInstance(2020, 2, 17);
        }
        else{
           d = Date.newInstance(2025, 2, 17);
        } 
        
        Lending__c lending = new Lending__c(Name = 'Test Lending', Book__c = book.Id, User__c = u.Id, Start_Date__c = Date.newInstance(2015, 2, 17), End_Date__c=d);
        insert lending;
        
        return lending;
    }

}