force-app/main/default/objects/Lending__c/Lending__c.object-meta.xml
<CustomObject>
    <label>Lending</label>
    <nameField>
        <label>Lending Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lending__c/fields/isEnded__c.field-meta.xml
<CustomField>
    <fullName>isEnded__c</fullName>
    <description>Checks if the lending is ended</description>
    <formula>IF( NOT(ISNULL( End_Date__c )), IF( TODAY() &gt;  End_Date__c, true, false), false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isEnded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/StoreCompleted.cls
global class StoreCompleted implements Schedulable {
    
    global void execute(SchedulableContext ctx) {
        
        postToExternalSystem(); //Callout to external system
        
        //delete old completed lendings
        List<Lending__c> lendingsCompleted = [SELECT Id from lending__c where isEnded__c = true];
        delete lendingsCompleted;		
    }
    
    @future(callout = true) 
    global static void postToExternalSystem(){

        Http http = new Http();
		HttpRequest request = new HttpRequest();
		request.setEndpoint('http://www.mocky.io/v2/5bcef5d53300009000c246d3');
		request.setMethod('GET');
        HttpResponse response = http.send(request);
        
        if(response.getStatusCode()==200){
            System.debug('request succesful!');
        }
    }
}