force-app/main/default/objects/Lending__c/Lending__c.object-meta.xml
<CustomObject>
    <label>Lending</label>
    <nameField>
        <label>Lending Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lending__c/fields/isEnded__c.field-meta.xml
<CustomField>
    <fullName>isEnded__c</fullName>
    <description>Checks if the lending is ended</description>
    <formula>IF( NOT(ISNULL( End_Date__c )), IF( TODAY() &gt;  End_Date__c, true, false), false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isEnded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestStoreCompleted.cls
@isTest
global class TestStoreCompleted implements HttpCalloutMock {
    
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    
    // Implement this interface method
    global HTTPResponse respond(HTTPRequest request) {
        // Create a fake response
        HttpResponse response = new HttpResponse();
        response.setStatusCode(200);
        return response; 
    }
    @isTest static void testCallout(){
       Test.setMock(HttpCalloutMock.class, new TestStoreCompleted());
       Test.startTest();
       String jobId = System.schedule('SystemCalloutTest', CRON_EXP, new StoreCompleted());
       // Stopping the test will run the job synchronously
       Test.stopTest();
       List<Lending__c> lendings = new List<Lending__c>();
       lendings = [SELECT id from lending__c where isEnded__c = TRUE];
       System.assert(lendings.size()==0);
    }
}